# Generated by Django 5.1.1 on 2024-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_phone', models.CharField(max_length=12)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_work', models.CharField(max_length=30)),
            ],
        ),
    ]
