# Generated by Django 5.1.1 on 2024-10-07 08:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('project_tech', tinymce.models.HTMLField()),
                ('project_desc', tinymce.models.HTMLField()),
                ('project_image', models.FileField(upload_to='')),
                ('project_slug', models.CharField(max_length=30)),
            ],
        ),
    ]
